# Generated by Django 3.0.5 on 2020-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=100)),
                ('client_info', models.TextField(max_length=200)),
            ],
        ),
    ]
