# Generated by Django 3.0.5 on 2020-08-14 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klienci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_start_date', models.DateField(default=django.utils.timezone.now)),
                ('project_create_date', models.DateField(auto_now_add=True)),
                ('project_status', models.CharField(choices=[('Otwarty', 'otwarty'), ('Zamknięty', 'zamknięty')], default='Otwarty', max_length=10)),
                ('project_info', models.TextField(max_length=200)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klienci.Client')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
